spring.data.mongodb.host=mongodb-docker-database
spring.data.mongodb.port=27017
spring.data.mongodb.database=massive-consumption-company
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
server.error.include-message = always
